/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jasa_pengiriman_barang1;

import javax.swing.JOptionPane;
import java.util.Random;
import java.util.*;
/**
 *
 * @author Naufal
 */
public class mainFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
    }
        
    
    public void refresh() {
        Random resi = new Random();
        textResi.setText("K-" + resi.nextInt(10000));
        textNama.setText("");
        textAlamat.setText("");
        textPerKm.setText("");
        textBerat.setText("");
        textTotal.setText("");
        textBayar.setText("");
        textKembali.setText("");
        textHasil.setText("");
        textHP.setText("");
        listKota.setSelectedItem("= Pilih Kota =");
        JOptionPane.showMessageDialog(Menu, "Halaman sudah di refresh.");
    }
    
    public void bayar() {
        int bayar = Integer.parseInt(textBayar.getText());
        int total = Integer.parseInt(textTotal.getText());
        if (bayar < total) {
            JOptionPane.showMessageDialog(Menu, "Maaf, uang anda tidak mencukupi.");
            textBayar.setText("");
        } else if (textNama.getText().equals("")) {
            JOptionPane.showMessageDialog(Menu, "Mohon masukkan nama anda.");
        } else if (textHP.getText().equals("")) {
            JOptionPane.showMessageDialog(Menu, "Mohon masukkan nomor HP anda.");
        } else if (textAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(Menu, "Mohon masukkan alamat tujuan.");
        } else if (listKota.getSelectedItem().equals(0)) {
            JOptionPane.showMessageDialog(Menu, "Mohon pilih kota tujuan.");
            
        } else {
            int kembali = bayar-total;
            textKembali.setText(String.valueOf(kembali));
            
            textHasil.append("\nJASA PENGIRIMAN BARANG");
            Waktu();
            textHasil.append("\n============================");
            textHasil.append("\nNomor Resi : "+textResi.getText());
            textHasil.append("\nNama Pengirim : "+textNama.getText());
            textHasil.append("\nNomor HP : "+textHP.getText());
            textHasil.append("\nAlamat Tujuan : "+textAlamat.getText());
            textHasil.append("\nKota Tujuan : " + (String)listKota.getSelectedItem());
            textHasil.append("\nHarga per kilometer : Rp. "+textPerKm.getText());
            textHasil.append("\nBerat Barang : "+textBerat.getText()+ " kg");
            textHasil.append("\nTotal yang harus dibayar : Rp. "+textTotal.getText());
            textHasil.append("\nBAYAR : Rp. "+textBayar.getText());
            textHasil.append("\nKEMBALI : Rp. "+textKembali.getText());
            textHasil.append("\n============================");
        }
    }
    
    public void Waktu() {
         int detik, menit, jam, hari, bulan, tahun;
        GregorianCalendar date = new GregorianCalendar();
    
        String namabulan[] = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
        detik = date.get(Calendar.SECOND);
        menit = date.get(Calendar.MINUTE);
        jam =  date.get(Calendar.HOUR_OF_DAY);
        hari = date.get(Calendar.DAY_OF_MONTH);
        bulan = date.get(Calendar.MONTH);
        tahun = date.get(Calendar.YEAR);

        textHasil.append( "\n" +hari +" "+ namabulan[bulan] +" "+ tahun +"  " + jam + ":" + menit +  ":" + detik);
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Subtitle = new javax.swing.JLabel();
        Menu = new javax.swing.JTabbedPane();
        menuRegistrasi = new javax.swing.JPanel();
        labelResi = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelHP = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelKota = new javax.swing.JLabel();
        labelPerKm = new javax.swing.JLabel();
        labelBerat = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelBayar = new javax.swing.JLabel();
        labelKembali = new javax.swing.JLabel();
        textResi = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        textHP = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        textPerKm = new javax.swing.JTextField();
        textBerat = new javax.swing.JTextField();
        textTotal = new javax.swing.JTextField();
        textBayar = new javax.swing.JTextField();
        textKembali = new javax.swing.JTextField();
        listKota = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textHasil = new javax.swing.JTextArea();
        textKg = new javax.swing.JLabel();
        buttonProses = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        buttonBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        Title.setText("Jasa Pengiriman Barang ");

        Subtitle.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        Subtitle.setText("Jalan Ahmad Yani no. 48, Wates, Daerah Istimewa Yogyakarta, 50421");

        labelResi.setText("No Resi");

        labelNama.setText("Nama Pengirim");

        labelHP.setText("No HP");

        labelAlamat.setText("Alamat Tujuan");

        labelKota.setText("Kota Tujuan");

        labelPerKm.setText("Harga per Km");

        labelBerat.setText("Berat");

        labelTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTotal.setText("Total");

        labelBayar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labelBayar.setText("Bayar");

        labelKembali.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labelKembali.setText("Kembali");

        textResi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textResiActionPerformed(evt);
            }
        });
        Random resi = new Random();
        textResi.setText("K-" + resi.nextInt(10000));
        textResi.setEditable(false);

        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });

        textPerKm.setEditable(false);

        textBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBeratActionPerformed(evt);
            }
        });

        textTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTotalActionPerformed(evt);
            }
        });
        textTotal.setEditable(false);

        textBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBayarActionPerformed(evt);
            }
        });

        textKembali.setEditable(false);

        listKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "= Pilih Kota =", "Jakarta", "Bandung", "Surabaya", "Semarang" }));
        listKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listKotaActionPerformed(evt);
            }
        });
        listKota.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                listKotaPropertyChange(evt);
            }
        });

        textHasil.setColumns(20);
        textHasil.setRows(5);
        jScrollPane1.setViewportView(textHasil);
        textHasil.setEditable(false);

        textKg.setText("kg");

        buttonProses.setText("Proses");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });

        buttonRefresh.setText("Clear");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        buttonBayar.setText("Bayar");
        buttonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuRegistrasiLayout = new javax.swing.GroupLayout(menuRegistrasi);
        menuRegistrasi.setLayout(menuRegistrasiLayout);
        menuRegistrasiLayout.setHorizontalGroup(
            menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuRegistrasiLayout.createSequentialGroup()
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelBerat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPerKm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelKota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listKota, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textHP, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textPerKm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane1))
                            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                        .addComponent(textBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(textKg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(122, 122, 122)
                                .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(buttonBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 29, Short.MAX_VALUE))))
                    .addGroup(menuRegistrasiLayout.createSequentialGroup()
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                .addComponent(labelResi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textResi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(buttonProses, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuRegistrasiLayout.setVerticalGroup(
            menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuRegistrasiLayout.createSequentialGroup()
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelResi))
                            .addComponent(textResi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNama)
                            .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHP)
                            .addComponent(textHP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAlamat)
                            .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKota)
                            .addComponent(listKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPerKm)
                            .addComponent(textPerKm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuRegistrasiLayout.createSequentialGroup()
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBayar)
                            .addComponent(textBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKembali)
                            .addComponent(textKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(buttonBayar))
                    .addGroup(menuRegistrasiLayout.createSequentialGroup()
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBerat)
                            .addComponent(textBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textKg))
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuRegistrasiLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menuRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonProses)
                            .addComponent(buttonRefresh))))
                .addContainerGap())
        );

        Menu.addTab("Registrasi", menuRegistrasi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Menu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(Subtitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(Title)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(Subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBayarActionPerformed
        // TODO add your handling code here:
        bayar();
    }//GEN-LAST:event_buttonBayarActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesActionPerformed
        Object total;
        // TODO add your handling code here:
        switch (listKota.getSelectedIndex()) {
            case 1: {
                int berat = Integer.parseInt(textBerat.getText());
                total = 4000 * berat;
            }
            textTotal.setText(String.valueOf(total));
            break;
            default:
        }
        switch (listKota.getSelectedIndex()) {
            case 2: {
                int berat = Integer.parseInt(textBerat.getText());
                total = 6000 * berat;
            }
            textTotal.setText(String.valueOf(total));
            break;
            default:
        }
        switch (listKota.getSelectedIndex()) {
            case 3: {
                int berat = Integer.parseInt(textBerat.getText());
                total = 8000 * berat;
            }
            textTotal.setText(String.valueOf(total));
            break;
            default:
        }
        switch (listKota.getSelectedIndex()) {
            case 4: {
                int berat = Integer.parseInt(textBerat.getText());
                total = 10000 * berat;
            }
            textTotal.setText(String.valueOf(total));
            break;
            default:
        }
    }//GEN-LAST:event_buttonProsesActionPerformed

    private void listKotaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_listKotaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_listKotaPropertyChange

    private void listKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listKotaActionPerformed
        // TODO add your handling code here:
        switch (listKota.getSelectedIndex()) {
            case 1: {
                textPerKm.setText(String.valueOf(4000));
            }
        }
        switch (listKota.getSelectedIndex()) {
            case 2: {
                textPerKm.setText(String.valueOf(6000));
            }
        }
        switch (listKota.getSelectedIndex()) {
            case 3: {
                textPerKm.setText(String.valueOf(8000));
            }
        }
        switch (listKota.getSelectedIndex()) {
            case 4: {
                textPerKm.setText(String.valueOf(10000));
            }
        }
    }//GEN-LAST:event_listKotaActionPerformed

    private void textBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBayarActionPerformed

    private void textTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalActionPerformed

    private void textBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBeratActionPerformed

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void textResiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textResiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textResiActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    
       
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JLabel Subtitle;
    private javax.swing.JLabel Title;
    private javax.swing.JButton buttonBayar;
    private javax.swing.JButton buttonProses;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelBayar;
    private javax.swing.JLabel labelBerat;
    private javax.swing.JLabel labelHP;
    private javax.swing.JLabel labelKembali;
    private javax.swing.JLabel labelKota;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPerKm;
    private javax.swing.JLabel labelResi;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JComboBox<String> listKota;
    private javax.swing.JPanel menuRegistrasi;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textBayar;
    private javax.swing.JTextField textBerat;
    private javax.swing.JTextField textHP;
    public javax.swing.JTextArea textHasil;
    private javax.swing.JTextField textKembali;
    private javax.swing.JLabel textKg;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textPerKm;
    private javax.swing.JTextField textResi;
    private javax.swing.JTextField textTotal;
    // End of variables declaration//GEN-END:variables
}
